/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bank.screens;

import com.bank.exception.InvalidAccountNumberExceptions;
import com.bank.main.Customer;
import com.bank.main.Withdrawal;
import com.bank.pro.User2;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author sonuy
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtaccno = new javax.swing.JTextField();
        btnDeposit = new javax.swing.JButton();
        btnWithdrawal = new javax.swing.JButton();
        btnStatement = new javax.swing.JButton();
        btnAcc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblmsg = new javax.swing.JLabel();

        jLabel1.setText("Main Screen");

        btnDeposit.setText("Deposit");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        btnWithdrawal.setText("Withdrawal");
        btnWithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawalActionPerformed(evt);
            }
        });

        btnStatement.setText("Statement");
        btnStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatementActionPerformed(evt);
            }
        });

        btnAcc.setText("Create Account");
        btnAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccActionPerformed(evt);
            }
        });

        jLabel2.setText("Account Number");

        jLabel3.setText("Welcome User");

        lblmsg.setText("-----------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAcc)
                    .addComponent(btnDeposit))
                .addGap(61, 61, 61)
                .addComponent(btnWithdrawal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnStatement)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtaccno, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblmsg)
                    .addComponent(jLabel3))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(btnAcc)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeposit)
                    .addComponent(btnWithdrawal)
                    .addComponent(btnStatement))
                .addGap(43, 43, 43)
                .addComponent(lblmsg)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccActionPerformed
        // TODO add your handling code here:
        Account a=new Account(this);
        a.setVisible(true);
    }//GEN-LAST:event_btnAccActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        // TODO add your handling code here:
        String accno=txtaccno.getText();
        User2 b=new User2();
        try {
            b.checkacc(accno);
//            setLblmsg("Account Number Proper");
            Customer c=b.getdetails(accno);
            Deposit deposit =new Deposit(c,this);
            deposit.setVisible(true);
        } 
        catch (SQLException ex) {
ex.printStackTrace();    
        }
        catch (ClassNotFoundException ex) {
              ex.printStackTrace();
        }
        catch (InvalidAccountNumberExceptions ex) {
            setLblmsg(ex.getText());
      }
        
        
        
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnWithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawalActionPerformed
        // TODO add your handling code here:
        
         String accno=txtaccno.getText();
        User2 b=new User2();
        try {
            b.checkacc(accno);
//            setLblmsg("Account Number Proper");
            Customer c=b.getdetails(accno);
            Withdrawalsc  with =new Withdrawalsc(c,this);
            with.setVisible(true);
        } 
        catch (SQLException ex) {
ex.printStackTrace();    
        }
        catch (ClassNotFoundException ex) {
              ex.printStackTrace();
        }
        catch (InvalidAccountNumberExceptions ex) {
            setLblmsg(ex.getText());
      }
    }//GEN-LAST:event_btnWithdrawalActionPerformed

    private void btnStatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatementActionPerformed
        // TODO add your handling code here:
        String accno=txtaccno.getText();
        User2 b=new User2();
        try {
            b.checkacc(accno);
//            setLblmsg("Account Number Proper");
            Customer c=b.getdetails(accno);
            Statement st=new Statement(c);
//            Withdrawalsc  with =new Withdrawalsc(c,this);
            st.setVisible(true);
        } 
        catch (SQLException ex) {
ex.printStackTrace();    
        }
        catch (ClassNotFoundException ex) {
              ex.printStackTrace();
        }
        catch (InvalidAccountNumberExceptions ex) {
            setLblmsg(ex.getText());
      }
        
        
        
        
    }//GEN-LAST:event_btnStatementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    public String getLblmsg() {
        return lblmsg.getText();
    }

    public void setLblmsg(String lblmsg1) {
        lblmsg.setText(lblmsg1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcc;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnStatement;
    private javax.swing.JButton btnWithdrawal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblmsg;
    private javax.swing.JTextField txtaccno;
    // End of variables declaration//GEN-END:variables
}
